In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
a= np.random.randn(10)
a

array([ 0.01082516, -0.59532582,  1.39729092,  0.10084448,  0.91321702,
       -0.96072393, -0.57798038,  1.38899515, -0.70906058,  0.82730538])

In [9]:
B=np.random.randn(10)
B

array([-0.39867347, -1.90591363,  0.09388895, -1.66428376, -0.68531951,
       -1.31185544, -0.42047937,  1.15173233, -1.64274999,  0.65410892])

In [10]:
#binary functions
np.add(a,B)

array([-0.38784831, -2.50123945,  1.49117987, -1.56343928,  0.22789751,
       -2.27257937, -0.99845975,  2.54072748, -2.35181057,  1.4814143 ])

In [11]:
np.maximum(a,B)

array([ 0.01082516, -0.59532582,  1.39729092,  0.10084448,  0.91321702,
       -0.96072393, -0.42047937,  1.38899515, -0.70906058,  0.82730538])

In [15]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#avilable-ufuncs'
import webbrowser
webbrowser.open(website)

True